return {
	[tostring] = {Name = 'tostring'},
	[tonumber] = {Name = 'tonumber'},
	[type] = {Name = 'type'},
	[typeof] = {Name = 'typeof'},
	-- os library
	[os.time] = {Name = 'os.time'},
	[os.date] = {Name = 'os.date'},
	[os.difftime] = {Name = 'os.difftime'},
	-- string library
	[string.byte] = {Name = 'string.byte'},
	[string.char] = {Name = 'string.char'},
	[string.dump] = {Name = 'string.dump'},
	[string.find] = {Name = 'string.find'},
	[string.format] = {Name = 'string.format'},
	[string.gmatch] = {Name = 'string.gmatch'},
	[string.gsub] = {Name = 'string.gsub'},
	[string.len] = {Name = 'string.len'},
	[string.lower] = {Name = 'string.lower'},
	[string.match] = {Name = 'string.match'},
	[string.rep] = {Name = 'string.rep'},
	[string.reverse] = {Name = 'string.reverse'},
	[string.sub] = {Name = 'string.sub'},
	[string.upper] = {Name = 'string.upper'},
	-- math library
	[math.log] = {Name = 'math.log'},
	[math.ldexp] = {Name = 'math.ldexp'},
	[math.rad] = {Name = 'math.rad'},
	[math.cosh] = {Name = 'math.cosh'},
	[math.random] = {Name = 'math.random'},
	[math.frexp] = {Name = 'math.frexp'},
	[math.tanh] = {Name = 'math.tanh'},
	[math.floor] = {Name = 'math.floor'},
	[math.max] = {Name = 'math.max'},
	[math.sqrt] = {Name = 'math.sqrt'},
	[math.modf] = {Name = 'math.modf'},
--	[math.huge] = {Name = 'math.huge'},
	[math.pow] = {Name = 'math.pow'},
	[math.atan] = {Name = 'math.atan'},
	[math.tan] = {Name = 'math.tan'},
	[math.cos] = {Name = 'math.cos'},
	[math.sign] = {Name = 'math.sign'},
	[math.clamp] = {Name = 'math.clamp'},
	[math.log10] = {Name = 'math.log10'},
	[math.noise] = {Name = 'math.noise'},
	[math.acos] = {Name = 'math.acos'},
	[math.abs] = {Name = 'math.abs'},
--	[math.pi] = {Name = 'math.pi'},
	[math.sinh] = {Name = 'math.sinh'},
	[math.asin] = {Name = 'math.asin'},
	[math.min] = {Name = 'math.min'},
	[math.deg] = {Name = 'math.deg'},
	[math.fmod] = {Name = 'math.fmod'},
	[math.randomseed] = {Name = 'math.randomseed'},
	[math.atan2] = {Name = 'math.atan2'},
	[math.ceil] = {Name = 'math.ceil'},
	[math.sin] = {Name = 'math.sin'},
	[math.exp] = {Name = 'math.exp'},
	-- table library
	[table.setn] = {Name = 'table.setn'},
	[table.insert] = {Name = 'table.insert'},
	[table.getn] = {Name = 'table.getn'},
	[table.foreachi] = {Name = 'table.foreachi'},
	[table.maxn] = {Name = 'table.maxn'},
	[table.foreach] = {Name = 'table.foreach'},
	[table.concat] = {Name = 'table.concat'},
	[table.sort] = {Name = 'table.sort'},
	[table.remove] = {Name = 'table.remove'},
}
